// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetsLife_Adoptions.AccessData;

namespace AccessData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetsLife_Adoptions.Domain.Entities.Adoptante", b =>
                {
                    b.Property<int>("AdoptanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdoptanteId");

                    b.ToTable("Adoptantes");
                });

            modelBuilder.Entity("PetsLife_Adoptions.Domain.Entities.AdoptanteMascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdoptanteId")
                        .HasColumnType("int");

                    b.Property<int>("MascotaID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdoptanteId");

                    b.HasIndex("MascotaID");

                    b.ToTable("AdoptanteMascotas");
                });

            modelBuilder.Entity("PetsLife_Adoptions.Domain.Entities.Animal", b =>
                {
                    b.Property<int>("TipoAnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoAnimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoAnimalId")
                        .HasName("AnimalId");

                    b.ToTable("Animales");

                    b.HasData(
                        new
                        {
                            TipoAnimalId = 1,
                            TipoAnimal = "Canino"
                        },
                        new
                        {
                            TipoAnimalId = 2,
                            TipoAnimal = "Felino"
                        },
                        new
                        {
                            TipoAnimalId = 3,
                            TipoAnimal = "Reptil"
                        },
                        new
                        {
                            TipoAnimalId = 4,
                            TipoAnimal = "Roedor"
                        },
                        new
                        {
                            TipoAnimalId = 5,
                            TipoAnimal = "Anfibio"
                        },
                        new
                        {
                            TipoAnimalId = 6,
                            TipoAnimal = "Mamifero"
                        },
                        new
                        {
                            TipoAnimalId = 7,
                            TipoAnimal = "Acuatico"
                        },
                        new
                        {
                            TipoAnimalId = 8,
                            TipoAnimal = "Artropodo"
                        },
                        new
                        {
                            TipoAnimalId = 9,
                            TipoAnimal = "Insecto"
                        },
                        new
                        {
                            TipoAnimalId = 10,
                            TipoAnimal = "Ave"
                        },
                        new
                        {
                            TipoAnimalId = 11,
                            TipoAnimal = "Aracnido"
                        });
                });

            modelBuilder.Entity("PetsLife_Adoptions.Domain.Entities.Mascota", b =>
                {
                    b.Property<int>("MascotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Adoptado")
                        .HasColumnType("bit");

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Historia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.HasKey("MascotaId");

                    b.HasIndex("AnimalId");

                    b.ToTable("Mascotas");

                    b.HasData(
                        new
                        {
                            MascotaId = 1,
                            Adoptado = false,
                            AnimalId = 1,
                            Edad = 1,
                            Historia = "Se darán desparacitados. Faltan 2 semanas para que desteten y pueden irse a un hogar definitivo!!",
                            Imagen = "https://scontent.faep9-2.fna.fbcdn.net/v/t1.6435-9/203992742_287174139818403_7111540916636416702_n.jpg?_nc_cat=106&ccb=1-3&_nc_sid=730e14&_nc_eui2=AeG2rnFxKO0kDNCUKv-aFs7uCS0ud5s0Pt0JLS53mzQ-3b7thL_wiT9vWkkQ8aeIjC4hpGD2CsTERCui-2mxq9-t&_nc_ohc=6RZ4ZwAWuwsAX8rvyoU&_nc_ht=scontent.faep9-2.fna&oh=678793d7d4479262034af3c3f4884be2&oe=60F18064",
                            Nombre = "Morocha",
                            Peso = 1.0
                        },
                        new
                        {
                            MascotaId = 2,
                            Adoptado = false,
                            AnimalId = 1,
                            Edad = 3,
                            Historia = "Ella es una perrita de Berazategui que llevamos a castrar y tiene Dioctophyma",
                            Imagen = "https://scontent.faep9-1.fna.fbcdn.net/v/t1.6435-0/p180x540/191059195_10219931954945369_5336803052641565501_n.jpg?_nc_cat=100&ccb=1-3&_nc_sid=e3f864&_nc_eui2=AeFx6-ffV6qVqcZqzbiPmrih5UoO36HoWzjlSg7foehbOFAHKXbYj1_8w-I1pFWRBn8R83MGGe4FoDiKfiAx3aBX&_nc_ohc=hF6qS_fBD1UAX82TFdK&_nc_ht=scontent.faep9-1.fna&oh=24d84b85de6989caa9e1c89e550bc912&oe=60F0F42E",
                            Nombre = "Negra",
                            Peso = 12.0
                        },
                        new
                        {
                            MascotaId = 3,
                            Adoptado = false,
                            AnimalId = 2,
                            Edad = 1,
                            Historia = "Lo rescatamos junto a su hermano, Rómulo, de la calle cuando aún eran lactantes. Las probabilidades de que viva, como todo lactantes, eran mínimas. Remo fue criado a mamadera y por eso es súper mamero y cariñoso.",
                            Imagen = "https://scontent.faep9-2.fna.fbcdn.net/v/t1.6435-0/p480x480/191161072_269984801537337_2154404893509938942_n.jpg?_nc_cat=110&ccb=1-3&_nc_sid=730e14&_nc_eui2=AeHqOdgWF6EnhdSUbyj_7ZzqOcj9D4ko_JA5yP0PiSj8kPFxuomn-MPU6dqi140R2dXVf8w2wW7164O59Gn94He9&_nc_ohc=iJejTUWb7CQAX8LZGMV&_nc_ht=scontent.faep9-2.fna&oh=883400aa521e1e8e559653a0c9039d12&oe=60F21513",
                            Nombre = "Romulo",
                            Peso = 10.0
                        },
                        new
                        {
                            MascotaId = 4,
                            Adoptado = false,
                            AnimalId = 1,
                            Edad = 1,
                            Historia = "Maqui es una hembra de tamaño grande, tiene alrededor de un año y está castrada. Es muy tranquila y ama pasear, se lleva de maravilla con perros!! Pero no con gatos y niños.",
                            Imagen = "https://scontent.faep9-1.fna.fbcdn.net/v/t1.6435-9/170693894_238731724662645_1378015511004095585_n.jpg?_nc_cat=100&ccb=1-3&_nc_sid=730e14&_nc_eui2=AeGjA1uyjLs86IugqR0B4qnTJYKQqRyvSSclgpCpHK9JJ-5Hc5CtCssJRQ8Pc3EJAGs0XFxixlri5o0muBHMKIqP&_nc_ohc=RETEU6qh1ckAX_wX4x6&_nc_ht=scontent.faep9-1.fna&oh=74090e9e334c6491136b87ac4a29925d&oe=60F135C0",
                            Nombre = "Maqui",
                            Peso = 8.0
                        },
                        new
                        {
                            MascotaId = 5,
                            Adoptado = false,
                            AnimalId = 3,
                            Edad = 3,
                            Historia = "El es Pepe, es un loro hablador tiene aproximadamente 3 años y medio. Ya esta desparacitado.",
                            Imagen = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNSj4o_j4-Y4-DeZbBgYNksKbVDOwVeef4hBErRXzMbT7cDB5A8Fos7Ym6XnSEnXQq7wQ&usqp=CAU",
                            Nombre = "Pepe",
                            Peso = 1.0
                        });
                });

            modelBuilder.Entity("PetsLife_Adoptions.Domain.Entities.AdoptanteMascota", b =>
                {
                    b.HasOne("PetsLife_Adoptions.Domain.Entities.Adoptante", "Adoptantes")
                        .WithMany("AdoptanteMascota")
                        .HasForeignKey("AdoptanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetsLife_Adoptions.Domain.Entities.Mascota", "Mascotas")
                        .WithMany("AdoptanteMascota")
                        .HasForeignKey("MascotaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adoptantes");

                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("PetsLife_Adoptions.Domain.Entities.Mascota", b =>
                {
                    b.HasOne("PetsLife_Adoptions.Domain.Entities.Animal", "Animales")
                        .WithMany("Mascotas")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animales");
                });

            modelBuilder.Entity("PetsLife_Adoptions.Domain.Entities.Adoptante", b =>
                {
                    b.Navigation("AdoptanteMascota");
                });

            modelBuilder.Entity("PetsLife_Adoptions.Domain.Entities.Animal", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("PetsLife_Adoptions.Domain.Entities.Mascota", b =>
                {
                    b.Navigation("AdoptanteMascota");
                });
#pragma warning restore 612, 618
        }
    }
}
